comment:
   image:
     repository: alexeyaltunin/comment
     tag: latest
   service:
     externalPort: 9292

 post:
   image:
     repository: alexeyaltunin/post
     tag: latest
     service:
       externalPort: 5000

 ui:
   image:
     repository: alexeyaltunin/ui
     tag: latest
     service:
       externalPort: 9292

