kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: s4kUNAzV1NSVd0slf6EeSAfae+d+UNeGKbjbv4w8aws=
      - identity: {}
